#cloud-config

package_update: true

packages:
  - build-essential
  - unzip
  - gfortran
  - ninja-build
  - cmake
  - python3-dev
  - python-is-python3
  - python3-venv
  - tree
  - ncdu
  - ripgrep

write_files:
  - content: |
      mirrors:
        local_filesystem: file:///home/ubuntu/mirror
    path: /home/ubuntu/.spack/mirrors.yaml
    permissions: '0644'
  - content: |
      . /home/ubuntu/spack/share/spack/setup-env.sh
      spack env activate /home/ubuntu/nantes-m2-rps-exp/qqbar2mumu-2021
      spack load qqbar2mumu-2021
      jupyter lab --no-browser --ip $(hostname -I | cut -d ' ' -f 1) --notebook-dir /home/ubuntu/nantes-m2-rps-exp/qqbar2mumu-2021
    path: /usr/local/bin/start
    permissions: '0755'
  - content: |
      packages:
        all:
          target: ['aarch64']
    path: /home/ubuntu/.spack/linux/packages.yaml
    permissions: '0644'

runcmd:
    - git clone "https://github.com/nantes-m2-rps-exp/spack-repo" /home/ubuntu/nantes-m2-rps-exp/spack-repo
    - git clone "https://github.com/nantes-m2-rps-exp/qqbar2mumu-2021" /home/ubuntu/nantes-m2-rps-exp/qqbar2mumu-2021
    - git clone -c feature.manyFiles=true "https://github.com/spack/spack.git" /home/ubuntu/spack
    - cd /home/ubuntu/spack && git checkout 5319b6e3b1fb4217fe57cbbf511bb9757b7afa31
    - curl -L https://cernbox.cern.ch/index.php/s/u8aCYh5fdB0Viuf/download -o /home/ubuntu/mirror.tar.gz
    - cd /home/ubuntu && tar -zvxf /home/ubuntu/mirror.tar.gz && rm mirror.tar.gz
    - mkdir /data
    - chown -R ubuntu.ubuntu /home/ubuntu/

final_message: "The system is finally up, after $UPTIME seconds"

